# ----------------------------------
#   Configuration file for RankSay
# ----------------------------------

# Essentials color chars work here
#		Placeholders also work:
#			- %MESSAGE%
#			- %RANK%
#			- %PLAYER_PREFIX%
#			- %DISPLAY_NAME%
#			- %PLAYER_NAME%
#
format: '[%PLAYER_PREFIX%]: %MESSAGE%'